### ISSUE TITLE
Backend 메인 기술스택 변경

### ISSUE THREAD

**Issue by AMinSC** [com-maeng/cali#101]
Django -> Spring Boot
기존 Django에서 Spring Boot로 백엔드를 재구성합니다.

- [ ] 프로젝트에 적합한 버전 서칭
- [ ] 자바 & 스프링 컨벤션 서칭
- [ ] 스프링부트를 사용한 이유 등 README 작성
- [ ] 베이스 설정 (postgres 설정 등)

**Comment by com-maeng** [comment]
@AMinSC 왜 스프링 부트를 쓰는지 이유가 있으면 좋을 것 같습니다~
