### ISSUE TITLE
'전서' 작품 조회 API 구현

### ISSUE THREAD

**Issue by com-maeng** [com-maeng/cali#102]
## Description

작품 검색 후 '검색결과' 페이지의 '전서' 탭에서 보여질 작품들을 조회할 수 있도록 API를 구현합니다.
구현된 API는 클라이언트(사용자) 측에서 호출하며, 작품 데이터를 담고 있는 GCS 버킷과 상호작용합니다.

## TODO

- [ ] ...

**Comment by jwhan12** [comment]
테스트
