### ISSUE TITLE
Wireframe 기반 UI 디자인 구체화

### ISSUE THREAD

**Issue by jwhan12** [com-maeng/cali#13]
Figma를 활용하여 기존에 제작했던 Wireframe을 토대로 유저 인터페이스(UI) 디자인을 설계합니다.

**Comment by jwhan12** [comment]
[[Cali] UI Design](https://www.figma.com/design/72q47vIkkINFcvHgMPU3Xp/%5BCali%5D-UI-Design?t=eRsRjCEeWhrowxte-1) 피그마 링크입니다.

**Comment by com-maeng** [comment]
@jwhan12 지원님 해당 이슈는 닫고 페이지별로 이슈 생성하시는 식으로 하셔도 될 것 같은데, 어떠신가용~
굳이 페이지별이 아니더라도 작업하시기 편한 단위로 하셔도 됩니다!

**Comment by jwhan12** [comment]
넵 알겠습니다. 리뷰 필요한 페이지의 경우 이슈 생성하여 진행하도록 하겠습니다!
(대부분 진행될 예정..)

**Comment by com-maeng** [comment]
체고체고~~~
(이슈는 제가 닫을게용!)
