### ISSUE TITLE
 메일리서치 메서드 수정

### ISSUE THREAD

**Issue by AMinSC** [com-maeng/cali#23]
- 검색 시 불필요한 작업(documents added) 제거
- [x] 메일리서치 메서드 수정
  - [x] 검색 시 불필요한 작업 제거
  - [x] 단일책임 원칙 지향
- [x] 메일리서치 문서 추가 작업 방법 알아보기
  - [ ] 스케줄링
  - [ ] #27
  - [ ] 그외

**Comment by com-maeng** [comment]
@AMinSC 성철님 제가 할 작업이 어떤 걸까용!!!

**Comment by AMinSC** [comment]
안녕하세요
작업중이신 스플릿된 한자데이터 GCS 적제 파이프라인 작업중 적제시 트리거 기반으로 작동 가능할지 의논 및 필요하다면 작업이 필요할것 같습니다
(버켓 변동 감지기반일 경우 파이프라인 작업과 무관하다면 제가 작업하겠습니다)

**Comment by com-maeng** [comment]
파이프라인에서 OCR 모듈을 통해 한자가 라벨링 되면(e.g., 土 흙 토) 해당 한자 이미지를 버킷에 적재하고, 버킷 적재 이후 메일리서치에 add_document 하는 식으로 진행하면 될 것 같습니다!
해당 작업은 제가 해도 될 것 같아용!

**Comment by com-maeng** [comment]
Assignees에서 저는 제외하겠습니당~
