### ISSUE TITLE
트리거 기반 이벤트(문서 재설정)

### ISSUE THREAD

**Issue by AMinSC** [com-maeng/cali#27]
docker container가 올라간 상태에서 django file이 수정되면 meilisearch documents 재생성 (정확히 얘기하자면 DI Container 세팅한 class 객체가 재생성되는 것으로 판단)
- DEBUG=True 인 상태에서 위와 같이 작동하더라도 product 상황인 DEBUG=False 상황에서는 별도 트리거 작업 필요
- GCS API로 S3 데이터 상태 변화를 감지할 수 있는지 확인 필요
- GCS API가 없다면, 작품 파이프라인 [#19](https://github.com/com-maeng/cali/issues/19) 작업을 감지할 수 있는지 확인

**Comment by com-maeng** [comment]
@AMinSC 디버그 모드라 하더라도 장고 애플리케이션이 재시작되면서 도큐먼트가 재생성되는 일은 없어야 될 것 같습니다!
해당 이슈 해결하려면 지난번에 말씀드렸던 코드 분리 및 장고 앱 로직 수정

**Comment by AMinSC** [comment]
안녕하세요
확인해본 결과 디버그모드일 경우 개발환경 변화를 감지하기 위해 장고 내부적으로 재시동되는것으로 확인됩니다(호스팅하여 개발중 실시간 변화 감지를 위해, 예를 들어 코드로직이 전체 페이지를 조회하는 로직에서 필터링된 페이지를 조회하는 로직으로 변경 후 저장할 경우 파일 변화를 감지 후 재시동하여 호스팅을 내리고 올리지 않아도 실시간으로 변경된 로직을 확인)

다만, 코드 분리 및 로직 관련하여 좀더 보강 하도록 하겠습니다
감사합니다!

**Comment by AMinSC** [comment]
닫아도 될 것 같습니다아~!
