### ISSUE TITLE
아이콘 디자인 작업

### ISSUE THREAD

**Issue by jwhan12** [com-maeng/cali#37]
Cali 어플리케이션 내 사용할 아이콘을 Illustrator와 Figma로 디자인합니다. 
이후 피드백을 통해 수정 작업을 진행합니다.

**Comment by com-maeng** [comment]
@jwhan12 지원님! 리뷰 요청 전에는 `In progress` 컬럼에 위치시켜주세용~

**Comment by jwhan12** [comment]
ㅎㅎㅎ 감사합니다! 😄

**Comment by com-maeng** [comment]
쵝 오 👍🏻
