### ISSUE TITLE
Meilisearch 모듈 만들기

### ISSUE THREAD

**Issue by AMinSC** [com-maeng/cali#42]
- 검색엔진으로 사용할 Meilisearch OSS 모듈을 루트 경로에 만듭니다.
- 추가로 색인된 문서 생성과 검색 테스트 코드를 작성합니다.
- [x] #58
- [x] #61

**Comment by com-maeng** [comment]
@AMinSC 성철님 이거 이슈 닫으려는데 문제 없을지 확인 부탁드립니다!
