### ISSUE TITLE
Meilisearch 초기 설정 기능과 관련 테스트코드 추가

### ISSUE THREAD

**Issue by AMinSC** [com-maeng/cali#58]
#### Meilisearch 초기 설정 클래스

- Client, index 및 문서 추가와 필터링 기준 필드값 정의
- hanjaDict.json 파일 전처리 함수 추가
- 관련 테스트 코드 작성

**Comment by com-maeng** [comment]
@AMinSC 이슈 제목을 조금만 더 자세히 적어주세용... 🙏🏻

**Comment by AMinSC** [comment]
#64
