### ISSUE TITLE
Meilisearch 검색 기능과 관련 테스트코드 추가

### ISSUE THREAD

**Issue by AMinSC** [com-maeng/cali#61]
#### Meilisearch 검색 클래스

- [x] 한자, 훈, 음으로 검색할 경우, 검색 엔진을 활용한 검색 결과 반환
- [ ] #76
- 관련 테스트 코드 작성
  - 검색 결괏값 확인
  - API 요청 인수값 확인

**Comment by com-maeng** [comment]
@AMinSC 성철님 이거 이슈 닫으려는데 문제 없을지 확인 부탁드립니다!
