### ISSUE TITLE
검색 모듈관련 싱글톤패턴 적용하기

### ISSUE THREAD

**Issue by AMinSC** [com-maeng/cali#90]
불필요한 인스턴스 생성을 보완하기 위해 검색 모듈의 Config, Search 클래스를 기반으로 싱글톤패턴 적용

**Comment by com-maeng** [comment]
@AMinSC 싱글톤 패턴이 메일리서치 모듈을 말씀하시는 건가요...?

**Comment by AMinSC** [comment]
맞습니당.. 해당 작업은 독단적으로 할 생각은 없고, 인수인계 받으시고, 작업하시고 나서 미팅 후 진행 여부를 결정하려고 합니다

**Comment by com-maeng** [comment]
> 맞습니당.. 해당 작업은 독단적으로 할 생각은 없고, 인수인계 받으시고, 작업하시고 나서 미팅 후 진행 여부를 결정하려고 합니다

@AMinSC 싱글톤 관련해서 100%는 이해 못 했지만.... 얼개는 파악한 상태라 추가적인 인수인계는 미진행하는 것으로 하겠습니다!
성철님은 이제 장고 작업 부탁드리고, 나중에 '장고 사이드'에서 싱글톤 이슈가 발생하면 저한테 노티 부탁드려요!
